### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "tanvir3@gmail.com",
    "password": "6464664"
}

### Signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "tanvir3@gmail.com",
    "password": "6464664"
}


### Find a particular user with a given id
GET http://localhost:3000/auth/2

### Find a particular users with same email
GET http://localhost:3000/auth?email=tanvir@gmail.com

### Find all users
GET http://localhost:3000/auth

### Update a particular user with given a id and data 
PATCH  http://localhost:3000/auth/2
Content-Type: application/json

{
    "email": "hello@gmail.com",
    "password": "asdfasdf"
}

### Remove a particular user with a given id
DELETE  http://localhost:3000/auth/3